server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com     # eureka服务端的实例名称
  client:
    fetch-registry: false  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false   # false表示自己不需要向注册中心注册自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   # 集群版
  server:
    enable-self-preservation: false #关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 2000 #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms），测试环境修改小点